### ISSUE TITLE
Images not found

### ISSUE THREAD

**Issue by aravindaj1** [mahadev0811/BilledIn#1]
./Assert folder is not uploaded.
![Screenshot 2024-04-10 100604](https://github.com/mahadev0811/BilledIn/assets/159010358/397503f4-1657-446c-a776-dd02ede4b581)

**Comment by mahadev0811** [comment]
Hi @aravindaj1, Sorry for the late reply.
The images for this repo is proprietary so I couldn't upload them, but you can use the screenshots I have uploaded as reference to design your own templates.
I will try to upload all the images as early as possible
